language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
script: grunt
env:
  global:
  - secure: FILyoQl0JJccZDAWDj+sM3JLJBo9bQDZFMrfYiFRM8aERH8zAAYZ5NQgwfdXc4rizoYur8ptGnh9RFfioQv2bEZICHw5f47mDP9ybW0hJvMZkB6kbeeUt8Q817IQBa1Kl1UttP8Qj7NFgOJtf0WPU0M6mO9tviuNyHRwgzGp/IQ=
  - secure: MJ/iqdPSE7Awgup3pfbnmmXE/pMWSKRFYy/iC4H/q4p8COiddjlun0SttbJsnIKLgYQOfe2r5qlY1oPm+/36Xrfg4RTSlaJ6/L/xL7BgiEMq0KZl31sdADv74aluzKvkdL2LQs/RkzBslj1r1Tmeb3k9kVjUqyOZhik1yuo4z9Y=
