language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: MPJt3GB5+EfX3WRhGJCOynVkI3E9/63hHjIy92bl5dq/zspmaHtL+YGNL/Y6OKIqIP69a/YAEPs/QzuL5QBqiULthn7qvgFPpHSIzUxmhyfmTX0QeALn68be1EJ5rHX5T/nDc8z1hp7/Eeh296kxaOqp+OsrSEztTOXNnQ2WZ6k=
  - secure: HpToyzhWOAKlJj4dN37RM1Q08JJg8Dp1BNTv1NsG01gNIRI62K7oRs3JOZSqjcMbDwnGoHd+PovI6UokX0P1SBxNV6mtNXNvYr81Lf5R4qXMuvyhT0RnuOMljl5oWyryx/EOJnwCswM8y7zIBkTQu1qftWNjWRFHuc6RUn4tSbg=
